# Generated by Django 3.2 on 2022-06-07 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0002_auto_20220607_0918'),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_numero_cita', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario_atencion', models.IntegerField()),
                ('detalle', models.CharField(max_length=255)),
                ('fecha_cita', models.DateField()),
                ('hora', models.TimeField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id_tipo_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipo de Servicios',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.BooleanField(default=True)),
                ('id_tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='citas.tiposervicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.IntegerField(choices=[(0, 'Hembra'), (1, 'Macho')])),
                ('fecha_registro', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.cliente')),
                ('id_raza', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='citas.raza')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
        migrations.CreateModel(
            name='DetalleCitaServicio',
            fields=[
                ('id_detalle_cita_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=80)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='citas.cita')),
                ('id_servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='citas.servicio')),
            ],
            options={
                'verbose_name': 'DetalleCitaServicio',
                'verbose_name_plural': 'DetalleCitaServicios',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='id_mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='citas.mascota'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
